version: '3'
services:
  node1:
    build: .
    ports:
      - "9091:9091"
    networks:
      mynet:
        ipv4_address: 172.20.0.2
    command:
      - bash
  node2:
    build: .
    ports:
      - "9092:9092"
    networks:
      mynet:
        ipv4_address: 172.20.0.3
    command:
      - bash
networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16